version: 0.2

phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package
      - cp target/AWS101.jar application.jar  # Rename for clarity

artifacts:
  files:
    - application.jar
    - Procfile