version: 0.2

phases:
    build:
      commands:
        - echo packaging JAR file...
        - mvm clean package
        - cp target/AWS101.jar application.jar

  artifacts:
    files:
      - application.jar